### PR TITLE
Per-operation context + initial payload

### PR DESCRIPTION
**Pull request by AndreyMZ**
This pull request adds two features:
1. https://github.com/datadvance/DjangoChannelsGraphqlWs/commit/e86c5fe7f46cbc1f1c5a918f994dc31b2e3ed599 Per-operation context - allows sharing any data between different calls to `Subscription.publish` for the same subscription (and the same connection).
2. https://github.com/datadvance/DjangoChannelsGraphqlWs/commit/39d61be0eb491338bfb1cbfc21928a09a24cd095 Initial payload - allows sending an arbitrary "initial" response to a client as soon as it is subscribed (before any call to `Subscription.broadcast`).

I use them like so (in `schema.py`):

~~~schema.py
import channels_graphql_ws
import graphene
from channels_graphql_ws.operation_context import OperationContext
from graphene import ResolveInfo

from .task import Task

class TaskLogChanged(channels_graphql_ws.Subscription):
    class Arguments:
        id = graphene.Argument(graphene.NonNull(graphene.ID))

    content = graphene.Field(graphene.NonNull(graphene.List(graphene.NonNull(graphene.String))))
    begin = graphene.Field(graphene.NonNull(graphene.Int))
    end = graphene.Field(graphene.NonNull(graphene.Int))

    class Meta:
        initial_payload = None

    @staticmethod
    def subscribe(root: None, info: ResolveInfo, id: str) -> Optional[List[str]]:
        task = Task(id)
        return [task.uuid]

    @classmethod
    def trigger(cls, task: Task) -> None:
        cls.broadcast_sync(group=task.uuid, payload=None)

    @staticmethod
    def publish(payload: None, info: ResolveInfo, id: str) -> Union[TaskLogChanged, object]:
        assert isinstance(info.context, OperationContext)
        saved_cursor: int = info.context.operation_context.get('cursor', 0)

        task = Task(id)
        content, new_cursor = task.get_log(saved_cursor)

        if new_cursor == saved_cursor:
            assert len(list(content)) == 0
            return TaskLogChanged.SKIP
        else:
            info.context.operation_context['cursor'] = new_cursor
            return TaskLogChanged(content=content, begin=saved_cursor, end=new_cursor)
~~~

### CODE REVIEW

**Comment by AndreyMZ** [comment]
@prokher, is there something preventing this pull request from being merged?

**Comment by AndreyMZ** [comment]
@prokher, ping.

**Comment by fdev** [comment]
I've been looking for a way to have an initial payload, but am sad to see this pull request has been closed without any response from the maintainer(s).

**Comment by Luferov** [comment]
I think that this library is dying and I need to look for or write something else that will work with graphene 3. unfortunately.

**Pull request closed without merging**
